### ISSUE TITLE
提个bug

### ISSUE THREAD

**Issue by zolagz** [rqh656418510/vuepress-plugin-readmore-popular#2]
你好，在vuepress-theme-vdoing主题下使用插件是遇到bug;

主题：https://github.com/xugaoyi/vuepress-theme-vdoing

![](https://tva1.sinaimg.cn/large/e6c9d24egy1h3v575d302j21j50u0agj.jpg)

当存在目录的时候，点击目录，内容页面会展示出来。
期望：存在目录的时候，点击目录，一样需要扫码查看。

**Comment by rqh656418510** [comment]
谢谢反馈，目前针对文章目录的问题，Hexo 博客是有针对性处理的，但由于 VuePress 主题比较难统一处理，所以一直都没有解决这问题。我尝试忽略目录的点击事件，或者按照你的建议点击目录后提示扫码。

**Comment by rqh656418510** [comment]
目前在文章未解锁的状态下，点击文章目录默认会显示二维码窗口了。此次更新不需要升级 VuePress 引流插件的版本，强制刷新 Web 页面即可生效，例如使用快捷键 `Ctrl + F5` 刷新页面。
